#ifndef YAHBOOM_FIRMWARE_VERSION_H
#define YAHBOOM_FIRMWARE_VERSION_H

#define FIRMWARE_VERSION_MAJOR  (1U)
#define FIRMWARE_VERSION_MINOR  (2U)
#define FIRMWARE_VERSION_PATCH  (0U)
#define FIRMWARE_VERSION_STRING "1.2.0-dev"
#define FIRMWARE_VERSION_TAG    "line-follower-v1.2.0-dev"

#endif
